version: 2
updates:
  # Rollkit specific updates
  # Trigger daily, group minor and patch updates
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    allow:
      - dependency-name: "rollkit/*"
    labels:
      - T:dependencies
    groups:
      patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    allow:
      - dependency-name: "github.com/rollkit/*"
    labels:
      - T:dependencies
    # Group all patch updates into a single PR
    groups:
      patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
          - "minor"
  # All other dependencies
  # Trigger weekly, group patch updates
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - T:dependencies
    groups:
      patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - T:dependencies
    groups:
      patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
